//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

contract EGoldNul {
    // THIS IS EGOLD NULL CONTRACT FOR STORING LP ACCURED IN AUCTION AND AS A PROOF OF TRANSPERANCY THAT NO ONE CAN WITHDRAW TOKENS FROM THIS CONTRACT
}