// SPDX-License-Identifier: AGPL-3.0

pragma solidity 0.6.12;
pragma experimental ABIEncoderV2;

import { BaseStrategy, StrategyParams } from "BaseStrategy.sol";
import { IERC20 } from "IERC20.sol";
import { SafeMath } from "SafeMath.sol";
import { SafeERC20 } from "SafeERC20.sol";
import { Address } from "Address.sol";
import { ERC20 } from "ERC20.sol";
import { Math } from "Math.sol";

import { ILpDepositor } from "ILpDepositor.sol";
import { IThenaRouter, route } from "IThenaRouter.sol";
import { IUniRouter } from "IUniswapV2Router02.sol";
import { IV1Pair } from "IThenaV1Pair.sol";

contract Strategy is BaseStrategy {
	using SafeERC20 for IERC20;
	using Address for address;
	using SafeMath for uint256;

	/**
	 * @dev Tokens Used:
	 * {wbnb} - Required for liquidity routing when doing swaps.
	 * {thenaReward} - Token generated by staking our funds.
	 * {thenaLp} - LP Token for Thena exchange.
	 * {want} - Tokens that the strategy maximizes. IUniswapV2Pair tokens.
	 */
	address internal constant wbnb = address(0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c); // WBNB
	address public constant thenaReward = address(0xF4C8E32EaDEC4BFe97E0F595AdD0f4450a863a11); // THENA
	address internal constant busd = address(0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56); // BUSD
	address internal constant dola = address(0x2F29Bc0FFAF9bff337b31CBe6CB5Fb3bf12e5840); // DOLA

	address public constant router = address(0x20a304a7d126758dfe6B243D0fc515F83bCA8431); // Thena Router
	ILpDepositor public masterChef; // {masterChef} - Depositor contract for Thena

	IV1Pair public thenaLp;
	IERC20 public token0;
	IERC20 public token1;

	uint256 public dust;
	uint256 public rewardDust;

	uint256 public maxSlippageIn; // bps
	uint256 public maxSlippageOut; // bps

	bool internal abandonRewards;

	bool internal immutable isStable;
	uint256 internal constant basisOne = 10000;
	uint256 internal constant MAX = type(uint256).max;

	uint256 public minProfit;
	bool internal forceHarvestTriggerOnce;

	address internal constant voterTHE = 0x981B04CBDCEE0C510D331fAdc7D6836a77085030; // We send some extra THE here
	uint256 public keepTHE; // Percentage of THE we re-lock for boost (in basis points)

	constructor(
		address _vault,
		address _masterChef,
		address _thenaLp
	) public BaseStrategy(_vault) {
		require(_thenaLp == address(want), "Wrong lpToken");

		thenaLp = IV1Pair(_thenaLp);
		isStable = thenaLp.isStable();

		token0 = IERC20(thenaLp.token0());
		token1 = IERC20(thenaLp.token1());

		maxSlippageIn = 1;
		maxSlippageOut = 1;

		maxReportDelay = 30 days;
		minProfit = 1e21;

		keepTHE = 2000;

		dust = 10**uint256((ERC20(address(want)).decimals()));
		rewardDust = 10**uint256((ERC20(address(thenaReward)).decimals()));

		masterChef = ILpDepositor(_masterChef);
		require(masterChef.TOKEN() == address(want), "Wrong masterChef");

		assert(masterChef.rewardToken() == thenaReward);

		_giveAllowances();
	}

	//-------------------------------//
	//       Public View func        //
	//-------------------------------//

	function name() external view override returns (string memory) {
		return string(abi.encodePacked("ThenaStrategy ", "Pool ", ERC20(address(want)).symbol()));
	}

	function estimatedTotalAssets() public view override returns (uint256) {
		return balanceOfWant().add(balanceOfLPInMasterChef());
	}

	function balanceOfWant() public view returns (uint256) {
		return want.balanceOf(address(this));
	}

	function balanceOfLPInMasterChef() public view returns (uint256 _amount) {
		_amount = masterChef.balanceOf(address(this));
	}

	function balanceOfReward() public view returns (uint256 _thenaRewards) {
		_thenaRewards = IERC20(thenaReward).balanceOf(address(this));
	}

	function pendingRewards() public view returns (uint256 _thenaBalance) {
		_thenaBalance = masterChef.earned(address(this));
	}

	function estimatedHarvest() public view returns (uint256 profitInBusd) {
		uint256 thenaBalance = pendingRewards().add(balanceOfReward());

		(uint256 profitInWbnb, ) = IThenaRouter(router).getAmountOut(
			thenaBalance,
			thenaReward,
			wbnb
		);

		(profitInBusd, ) = IThenaRouter(router).getAmountOut(profitInWbnb, wbnb, busd);
	}

	//-------------------------------//
	//      Internal Core func       //
	//-------------------------------//

	function prepareReturn(uint256 _debtOutstanding)
		internal
		override
		returns (
			uint256 _profit,
			uint256 _loss,
			uint256 _debtPayment
		)
	{
		// Claim THENA rewards
		_claimRewards();
		// Send some THENA to voter
		_sendToVoter();
		// Swap THENA for wBNB
		_sellRewards();
		// Swap wBNB to intermediate
		_convertToIntermediate();
		// Swap wBNB for token0 & token1 and build the LP
		_convertToLpToken();

		uint256 assets = estimatedTotalAssets();
		uint256 wantBalance = balanceOfWant();
		uint256 debt = vault.strategies(address(this)).totalDebt;

		_debtPayment = _debtOutstanding;
		uint256 amountToFree = _debtPayment.add(_profit);

		if (assets >= debt) {
			_debtPayment = _debtOutstanding;
			_profit = assets.sub(debt);

			amountToFree = _profit.add(_debtPayment);

			if (amountToFree > 0 && wantBalance < amountToFree) {
				liquidatePosition(amountToFree);

				uint256 newLoose = balanceOfWant();

				// If we dont have enough money adjust _debtOutstanding and only change profit if needed
				if (newLoose < amountToFree) {
					if (_profit > newLoose) {
						_profit = newLoose;
						_debtPayment = 0;
					} else {
						_debtPayment = Math.min(newLoose.sub(_profit), _debtPayment);
					}
				}
			}
		} else {
			// Serious loss should never happen but if it does lets record it accurately
			_loss = debt.sub(assets);
		}

		// We're done harvesting, so reset our trigger if we used it
		forceHarvestTriggerOnce = false;
	}

	/**
	 * @notice
	 *  In simple autocompounding adjustPosition only deposits the LpTokens in masterChef.
	 */
	function adjustPosition(uint256 _debtOutstanding) internal override {
		// Lp assets before the operation
		uint256 pooledBefore = balanceOfLPInMasterChef();

		uint256 amountIn = balanceOfWant();
		if (amountIn > dust) {
			// Deposit all LpTokens in Thena masterChef
			_depositLpIntoMasterChef();
			_enforceSlippageIn(amountIn, pooledBefore);
		}
	}

	function liquidatePosition(uint256 _amountNeeded)
		internal
		override
		returns (uint256 _liquidatedAmount, uint256 _loss)
	{
		if (estimatedTotalAssets() <= _amountNeeded) {
			_liquidatedAmount = liquidateAllPositions();
			return (_liquidatedAmount, _amountNeeded.sub(_liquidatedAmount));
		}

		uint256 looseAmount = balanceOfWant();
		if (_amountNeeded > looseAmount) {
			uint256 toExitAmount = _amountNeeded.sub(looseAmount);

			_withdrawLpFromMasterChef(toExitAmount);

			_liquidatedAmount = Math.min(balanceOfWant(), _amountNeeded);
			_loss = _amountNeeded.sub(_liquidatedAmount);

			_enforceSlippageOut(toExitAmount, _liquidatedAmount.sub(looseAmount));
		} else {
			_liquidatedAmount = _amountNeeded;
		}
	}

	function liquidateAllPositions() internal override returns (uint256 _liquidated) {
		uint256 eta = estimatedTotalAssets();

		_withdrawLpFromMasterChef(balanceOfLPInMasterChef());

		_liquidated = balanceOfWant();

		_enforceSlippageOut(eta, _liquidated);
	}

	/**
	 * @notice
	 *  This withdraws Lp tokens and transfers them into newStrategy.
	 */
	function prepareMigration(address _newStrategy) internal override {
		_withdrawFromMasterChefAndTransfer(_newStrategy);
	}

	//-------------------------------//
	//      Internal Swap func       //
	//-------------------------------//

	/**
	 * @notice
	 *  Swaps THENA for wBNB.
	 */
	function _sellRewards() internal {
		route[] memory thenaToWbnbRoute = new route[](1);
		thenaToWbnbRoute[0] = route(thenaReward, wbnb, false);

		uint256 thenaRewards = balanceOfReward();

		if (thenaRewards > rewardDust) {
			// THENA to wBNB
			IThenaRouter(router).swapExactTokensForTokens(
				thenaRewards,
				1,
				thenaToWbnbRoute,
				address(this),
				block.timestamp
			);
		}
	}

	function _sendToVoter() internal {
		uint256 thenaBalance = balanceOfReward();
		uint256 sendToVoter = thenaBalance.mul(keepTHE).div(basisOne);

		if (sendToVoter > 0) {
			IERC20(thenaReward).safeTransfer(voterTHE, sendToVoter);
		}
	}

	/**
	 * @notice
	 *  Swaps half of the wBNB for DOLA.
	 */
	function _convertToIntermediate() internal {
		route[] memory wbnbToDolaRoute = new route[](1);
		wbnbToDolaRoute[0] = route(wbnb, dola, false);

		uint256 wbnbBalance = IERC20(wbnb).balanceOf(address(this));

		if (wbnbBalance > 1e12) {
			IThenaRouter(router).swapExactTokensForTokens(
				wbnbBalance,
				1,
				wbnbToDolaRoute,
				address(this),
				block.timestamp
			);
		}
	}

	/**
	 * @notice
	 *  Swaps half of the DOLA for token0 and token1 and adds liquidity.
	 */
	function _convertToLpToken() internal {
		route[] memory dolaToToken0Route = new route[](1);
		dolaToToken0Route[0] = route(dola, address(token0), true);

		route[] memory dolaToToken1Route = new route[](1);
		dolaToToken1Route[0] = route(dola, address(token1), true);

		uint256 dolaBalance = IERC20(dola).balanceOf(address(this));

		if (dolaBalance > 1e16) {
			// If token0 or token1 is dola we skip the swap
			if (address(token0) != dola) {
				// 1/2 dola to token0
				IThenaRouter(router).swapExactTokensForTokens(
					dolaBalance.div(2),
					1,
					dolaToToken0Route,
					address(this),
					block.timestamp
				);
			}
			if (address(token1) != dola) {
				// 1/2 dola to token1
				IThenaRouter(router).swapExactTokensForTokens(
					dolaBalance.div(2),
					1,
					dolaToToken1Route,
					address(this),
					block.timestamp
				);
			}
		}

		// Add liquidity to build the LpToken
		uint256 token0Balance = IERC20(token0).balanceOf(address(this));
		uint256 token1Balance = IERC20(token1).balanceOf(address(this));

		if (token0Balance > 0 && token1Balance > 0) {
			_addLiquidity(token0Balance, token1Balance);
		}
	}

	//-------------------------------//
	//    Internal Liquidity func    //
	//-------------------------------//

	/**
	 * @notice
	 *  Add liquidity to Thena.
	 */
	function _addLiquidity(uint256 token0Amount, uint256 token1Amount) internal {
		IThenaRouter(router).addLiquidity(
			address(token0),
			address(token1),
			isStable,
			token0Amount,
			token1Amount,
			0,
			0,
			address(this),
			block.timestamp
		);
	}

	//--------------------------------//
	//    Internal MasterChef func    //
	//--------------------------------//

	/**
	 * @notice
	 *  Deposits all the LpTokens in masterChef.
	 */
	function _depositLpIntoMasterChef() internal {
		uint256 balanceOfLpTokens = balanceOfWant();
		if (balanceOfLpTokens > 0) {
			masterChef.deposit(balanceOfLpTokens);
		}
	}

	/**
	 * @notice
	 *  Withdraws a certain amount from masterChef.
	 */
	function _withdrawLpFromMasterChef(uint256 amount) internal {
		uint256 toWithdraw = Math.min(amount, balanceOfLPInMasterChef());
		if (toWithdraw > 0) {
			masterChef.withdraw(toWithdraw);
		}
	}

	/**
	 * @notice
	 *  Claim all THENA rewards from masterChef.
	 */
	function _claimRewards() internal {
		masterChef.getReward();
	}

	/**
	 * @notice
	 *  AbandonRewards withdraws lp without rewards.
	 * @dev
	 *  Specify where to withdraw to.
	 */
	function _withdrawFromMasterChefAndTransfer(address _to) internal {
		if (abandonRewards) {
			_withdrawLpFromMasterChef(balanceOfLPInMasterChef());
		} else {
			_claimRewards();
			_withdrawLpFromMasterChef(balanceOfLPInMasterChef());
			uint256 _thenaRewards = balanceOfReward();
			IERC20(thenaReward).safeTransfer(_to, _thenaRewards);
		}
		uint256 lpTokensBalance = balanceOfWant();
		if (lpTokensBalance > 0) {
			IERC20(address(thenaLp)).safeTransfer(_to, lpTokensBalance);
		}
	}

	//-------------------------------//
	//     Internal Helpers func     //
	//-------------------------------//

	function _giveAllowances() internal {
		IERC20(address(thenaLp)).safeApprove(address(masterChef), 0);
		IERC20(address(thenaLp)).safeApprove(address(masterChef), MAX);

		IERC20(address(thenaLp)).safeApprove(router, 0);
		IERC20(address(thenaLp)).safeApprove(router, MAX);

		IERC20(wbnb).safeApprove(router, 0);
		IERC20(wbnb).safeApprove(router, MAX);

		IERC20(dola).safeApprove(router, 0);
		IERC20(dola).safeApprove(router, MAX);

		IERC20(thenaReward).safeApprove(router, 0);
		IERC20(thenaReward).safeApprove(router, MAX);

		IERC20(token0).safeApprove(router, 0);
		IERC20(token0).safeApprove(router, MAX);

		IERC20(token1).safeApprove(router, 0);
		IERC20(token1).safeApprove(router, MAX);
	}

	/**
	 * @notice
	 *  Revert if slippage out exceeds our requirement.
	 * @dev
	 *  Enforce that amount exited didn't slip beyond our tolerance.
	 *  Check for positive slippage, just in case.
	 */
	function _enforceSlippageOut(uint256 _intended, uint256 _actual) internal view {
		uint256 exitSlipped = _intended > _actual ? _intended.sub(_actual) : 0;
		uint256 maxLoss = _intended.mul(maxSlippageOut).div(basisOne);
		require(exitSlipped <= maxLoss, "Slipped Out!");
	}

	/**
	 * @notice
	 *  Revert if slippage in exceeds our requirement.
	 * @dev
	 *  Enforce that amount exchange from want to LP tokens didn't slip beyond our tolerance.
	 *  Check for positive slippage, just in case.
	 */
	function _enforceSlippageIn(uint256 _amountIn, uint256 _pooledBefore) internal view {
		uint256 pooledDelta = balanceOfLPInMasterChef().sub(_pooledBefore);
		uint256 joinSlipped = _amountIn > pooledDelta ? _amountIn.sub(pooledDelta) : 0;
		uint256 maxLoss = _amountIn.mul(maxSlippageIn).div(basisOne);
		require(joinSlipped <= maxLoss, "Slipped in!");
	}

	function protectedTokens() internal view override returns (address[] memory) {}

	//-----------------------------//
	//    Public Triggers func     //
	//-----------------------------//

	/**
	 * @notice
	 *  Use this to determine when to harvest.
	 */
	function harvestTrigger(uint256 callCostInWei) public view override returns (bool) {
		StrategyParams memory params = vault.strategies(address(this));

		// Should not trigger if strategy is not active (no assets and no debtRatio)
		if (!isActive()) return false;

		// Trigger if profit generated is higher than minProfit
		if (estimatedHarvest() > minProfit) return true;

		// Harvest no matter what once we reach our maxDelay
		if (block.timestamp.sub(params.lastReport) > maxReportDelay) return true;

		// Trigger if we want to manually harvest, but only if our gas price is acceptable
		if (forceHarvestTriggerOnce) return true;

		// Otherwise, we don't harvest
		return false;
	}

	function ethToWant(uint256 _amtInWei) public view override returns (uint256) {}

	function tendTrigger(uint256 callCostInWei) public view override returns (bool) {
		return balanceOfWant() > 0;
	}

	//-------------------------------//
	//    Protected Setters func     //
	//-------------------------------//

	function setMinProfit(uint256 _minAcceptableProfit) external onlyKeepers {
		minProfit = _minAcceptableProfit;
	}

	/**
	 * @notice
	 *  This allows us to manually harvest with our keeper as needed.
	 */
	function setForceHarvestTriggerOnce(bool _forceHarvestTriggerOnce) external onlyKeepers {
		forceHarvestTriggerOnce = _forceHarvestTriggerOnce;
	}

	function setParams(uint256 _maxSlippageIn, uint256 _maxSlippageOut)
		external
		onlyVaultManagers
	{
		require(_maxSlippageIn <= basisOne);
		maxSlippageIn = _maxSlippageIn;

		require(_maxSlippageOut <= basisOne);
		maxSlippageOut = _maxSlippageOut;
	}

	function setDust(uint256 _dust, uint256 _rewardDust) external onlyVaultManagers {
		dust = _dust;
		rewardDust = _rewardDust;
	}

	function setKeep(uint256 _keepTHE) external onlyVaultManagers {
		require(_keepTHE <= 10_000, "Wrong input");
		keepTHE = _keepTHE;
	}

	/**
	 * @notice
	 *  Manually returns lps in masterChef to the strategy. Used in emergencies.
	 */
	function emergencyWithdrawFromMasterChef() external onlyVaultManagers {
		_withdrawLpFromMasterChef(balanceOfLPInMasterChef());
	}

	/**
	 * @notice
	 *  Toggle for whether to abandon rewards or not on emergency withdraws from masterChef.
	 */
	function setAbandonRewards(bool abandon) external onlyVaultManagers {
		abandonRewards = abandon;
	}

	receive() external payable {}
}

pragma experimental ABIEncoderV2;

import { IERC20 } from "IERC20.sol";
import { SafeMath } from "SafeMath.sol";
import { SafeERC20 } from "SafeERC20.sol";

struct StrategyParams {
	uint256 performanceFee;
	uint256 activation;
	uint256 debtRatio;
	uint256 minDebtPerHarvest;
	uint256 maxDebtPerHarvest;
	uint256 lastReport;
	uint256 totalDebt;
	uint256 totalGain;
	uint256 totalLoss;
}

interface VaultAPI is IERC20 {
	function name() external view returns (string calldata);

	function symbol() external view returns (string calldata);

	function decimals() external view returns (uint256);

	function apiVersion() external pure returns (string memory);

	function permit(
		address owner,
		address spender,
		uint256 amount,
		uint256 expiry,
		bytes calldata signature
	) external returns (bool);

	// NOTE: Vyper produces multiple signatures for a given function with "default" args
	function deposit() external returns (uint256);

	function deposit(uint256 amount) external returns (uint256);

	function deposit(uint256 amount, address recipient) external returns (uint256);

	// NOTE: Vyper produces multiple signatures for a given function with "default" args
	function withdraw() external returns (uint256);

	function withdraw(uint256 maxShares) external returns (uint256);

	function withdraw(uint256 maxShares, address recipient) external returns (uint256);

	function token() external view returns (address);

	function strategies(address _strategy) external view returns (StrategyParams memory);

	function pricePerShare() external view returns (uint256);

	function totalAssets() external view returns (uint256);

	function depositLimit() external view returns (uint256);

	function maxAvailableShares() external view returns (uint256);

	/**
	 * View how much the Vault would increase this Strategy's borrow limit,
	 * based on its present performance (since its last report). Can be used to
	 * determine expectedReturn in your Strategy.
	 */
	function creditAvailable() external view returns (uint256);

	/**
	 * View how much the Vault would like to pull back from the Strategy,
	 * based on its present performance (since its last report). Can be used to
	 * determine expectedReturn in your Strategy.
	 */
	function debtOutstanding() external view returns (uint256);

	/**
	 * View how much the Vault expect this Strategy to return at the current
	 * block, based on its present performance (since its last report). Can be
	 * used to determine expectedReturn in your Strategy.
	 */
	function expectedReturn() external view returns (uint256);

	/**
	 * This is the main contact point where the Strategy interacts with the
	 * Vault. It is critical that this call is handled as intended by the
	 * Strategy. Therefore, this function will be called by BaseStrategy to
	 * make sure the integration is correct.
	 */
	function report(
		uint256 _gain,
		uint256 _loss,
		uint256 _debtPayment
	) external returns (uint256);

	/**
	 * This function should only be used in the scenario where the Strategy is
	 * being retired but no migration of the positions are possible, or in the
	 * extreme scenario that the Strategy needs to be put into "Emergency Exit"
	 * mode in order for it to exit as quickly as possible. The latter scenario
	 * could be for any reason that is considered "critical" that the Strategy
	 * exits its position as fast as possible, such as a sudden change in
	 * market conditions leading to losses, or an imminent failure in an
	 * external dependency.
	 */
	function revokeStrategy() external;

	/**
	 * View the governance address of the Vault to assert privileged functions
	 * can only be called by governance. The Strategy serves the Vault, so it
	 * is subject to governance defined by the Vault.
	 */
	function governance() external view returns (address);

	/**
	 * View the management address of the Vault to assert privileged functions
	 * can only be called by management. The Strategy serves the Vault, so it
	 * is subject to management defined by the Vault.
	 */
	function management() external view returns (address);

	/**
	 * View the guardian address of the Vault to assert privileged functions
	 * can only be called by guardian. The Strategy serves the Vault, so it
	 * is subject to guardian defined by the Vault.
	 */
	function guardian() external view returns (address);
}

/**
 * This interface is here for the keeper bot to use.
 */
interface StrategyAPI {
	function name() external view returns (string memory);

	function vault() external view returns (address);

	function want() external view returns (address);

	function apiVersion() external pure returns (string memory);

	function keeper() external view returns (address);

	function isActive() external view returns (bool);

	function delegatedAssets() external view returns (uint256);

	function estimatedTotalAssets() external view returns (uint256);

	function tendTrigger(uint256 callCost) external view returns (bool);

	function tend() external;

	function harvestTrigger(uint256 callCost) external view returns (bool);

	function harvest() external;

	event Harvested(uint256 profit, uint256 loss, uint256 debtPayment, uint256 debtOutstanding);
}

interface HealthCheck {
	function check(
		uint256 profit,
		uint256 loss,
		uint256 debtPayment,
		uint256 debtOutstanding,
		uint256 totalDebt
	) external view returns (bool);
}

/**
 * @title Yearn Base Strategy
 * @author yearn.finance
 * @notice
 *  BaseStrategy implements all of the required functionality to interoperate
 *  closely with the Vault contract. This contract should be inherited and the
 *  abstract methods implemented to adapt the Strategy to the particular needs
 *  it has to create a return.
 *
 *  Of special interest is the relationship between `harvest()` and
 *  `vault.report()'. `harvest()` may be called simply because enough time has
 *  elapsed since the last report, and not because any funds need to be moved
 *  or positions adjusted. This is critical so that the Vault may maintain an
 *  accurate picture of the Strategy's performance. See  `vault.report()`,
 *  `harvest()`, and `harvestTrigger()` for further details.
 */

abstract contract BaseStrategy {
	using SafeMath for uint256;
	using SafeERC20 for IERC20;
	string public metadataURI;

	// health checks
	bool public doHealthCheck;
	address public healthCheck;

	/**
	 * @notice
	 *  Used to track which version of `StrategyAPI` this Strategy
	 *  implements.
	 * @dev The Strategy's version must match the Vault's `API_VERSION`.
	 * @return A string which holds the current API version of this contract.
	 */
	function apiVersion() public pure returns (string memory) {
		return "0.4.3";
	}

	/**
	 * @notice This Strategy's name.
	 * @dev
	 *  You can use this field to manage the "version" of this Strategy, e.g.
	 *  `StrategySomethingOrOtherV1`. However, "API Version" is managed by
	 *  `apiVersion()` function above.
	 * @return This Strategy's name.
	 */
	function name() external view virtual returns (string memory);

	/**
	 * @notice
	 *  The amount (priced in want) of the total assets managed by this strategy should not count
	 *  towards Yearn's TVL calculations.
	 * @dev
	 *  You can override this field to set it to a non-zero value if some of the assets of this
	 *  Strategy is somehow delegated inside another part of of Yearn's ecosystem e.g. another Vault.
	 *  Note that this value must be strictly less than or equal to the amount provided by
	 *  `estimatedTotalAssets()` below, as the TVL calc will be total assets minus delegated assets.
	 *  Also note that this value is used to determine the total assets under management by this
	 *  strategy, for the purposes of computing the management fee in `Vault`
	 * @return
	 *  The amount of assets this strategy manages that should not be included in Yearn's Total Value
	 *  Locked (TVL) calculation across it's ecosystem.
	 */
	function delegatedAssets() external view virtual returns (uint256) {
		return 0;
	}

	VaultAPI public vault;
	address public strategist;
	address public rewards;
	address public keeper;

	IERC20 public want;

	// So indexers can keep track of this
	event Harvested(uint256 profit, uint256 loss, uint256 debtPayment, uint256 debtOutstanding);

	event UpdatedStrategist(address newStrategist);

	event UpdatedKeeper(address newKeeper);

	event UpdatedRewards(address rewards);

	event UpdatedMinReportDelay(uint256 delay);

	event UpdatedMaxReportDelay(uint256 delay);

	event UpdatedProfitFactor(uint256 profitFactor);

	event UpdatedDebtThreshold(uint256 debtThreshold);

	event EmergencyExitEnabled();

	event UpdatedMetadataURI(string metadataURI);

	// The minimum number of seconds between harvest calls. See
	// `setMinReportDelay()` for more details.
	uint256 public minReportDelay;

	// The maximum number of seconds between harvest calls. See
	// `setMaxReportDelay()` for more details.
	uint256 public maxReportDelay;

	// The minimum multiple that `callCost` must be above the credit/profit to
	// be "justifiable". See `setProfitFactor()` for more details.
	uint256 public profitFactor;

	// Use this to adjust the threshold at which running a debt causes a
	// harvest trigger. See `setDebtThreshold()` for more details.
	uint256 public debtThreshold;

	// See note on `setEmergencyExit()`.
	bool public emergencyExit;

	// modifiers
	modifier onlyAuthorized() {
		require(msg.sender == strategist || msg.sender == governance(), "!authorized");
		_;
	}

	modifier onlyEmergencyAuthorized() {
		require(
			msg.sender == strategist ||
				msg.sender == governance() ||
				msg.sender == vault.guardian() ||
				msg.sender == vault.management(),
			"!authorized"
		);
		_;
	}

	modifier onlyStrategist() {
		require(msg.sender == strategist, "!strategist");
		_;
	}

	modifier onlyGovernance() {
		require(msg.sender == governance(), "!authorized");
		_;
	}

	modifier onlyKeepers() {
		require(
			msg.sender == keeper ||
				msg.sender == strategist ||
				msg.sender == governance() ||
				msg.sender == vault.guardian() ||
				msg.sender == vault.management(),
			"!authorized"
		);
		_;
	}

	modifier onlyVaultManagers() {
		require(msg.sender == vault.management() || msg.sender == governance(), "!authorized");
		_;
	}

	constructor(address _vault) public {
		_initialize(_vault, msg.sender, msg.sender, msg.sender);
	}

	/**
	 * @notice
	 *  Initializes the Strategy, this is called only once, when the
	 *  contract is deployed.
	 * @dev `_vault` should implement `VaultAPI`.
	 * @param _vault The address of the Vault responsible for this Strategy.
	 * @param _strategist The address to assign as `strategist`.
	 * The strategist is able to change the reward address
	 * @param _rewards  The address to use for pulling rewards.
	 * @param _keeper The adddress of the _keeper. _keeper
	 * can harvest and tend a strategy.
	 */
	function _initialize(
		address _vault,
		address _strategist,
		address _rewards,
		address _keeper
	) internal {
		require(address(want) == address(0), "Strategy already initialized");

		vault = VaultAPI(_vault);
		want = IERC20(vault.token());
		want.safeApprove(_vault, uint256(-1)); // Give Vault unlimited access (might save gas)
		strategist = _strategist;
		rewards = _rewards;
		keeper = _keeper;

		// initialize variables
		minReportDelay = 0;
		maxReportDelay = 86400;
		profitFactor = 100;
		debtThreshold = 0;

		vault.approve(rewards, uint256(-1)); // Allow rewards to be pulled
	}

	function setHealthCheck(address _healthCheck) external onlyVaultManagers {
		healthCheck = _healthCheck;
	}

	function setDoHealthCheck(bool _doHealthCheck) external onlyVaultManagers {
		doHealthCheck = _doHealthCheck;
	}

	/**
	 * @notice
	 *  Used to change `strategist`.
	 *
	 *  This may only be called by governance or the existing strategist.
	 * @param _strategist The new address to assign as `strategist`.
	 */
	function setStrategist(address _strategist) external onlyAuthorized {
		require(_strategist != address(0));
		strategist = _strategist;
		emit UpdatedStrategist(_strategist);
	}

	/**
	 * @notice
	 *  Used to change `keeper`.
	 *
	 *  `keeper` is the only address that may call `tend()` or `harvest()`,
	 *  other than `governance()` or `strategist`. However, unlike
	 *  `governance()` or `strategist`, `keeper` may *only* call `tend()`
	 *  and `harvest()`, and no other authorized functions, following the
	 *  principle of least privilege.
	 *
	 *  This may only be called by governance or the strategist.
	 * @param _keeper The new address to assign as `keeper`.
	 */
	function setKeeper(address _keeper) external onlyAuthorized {
		require(_keeper != address(0));
		keeper = _keeper;
		emit UpdatedKeeper(_keeper);
	}

	/**
	 * @notice
	 *  Used to change `rewards`. EOA or smart contract which has the permission
	 *  to pull rewards from the vault.
	 *
	 *  This may only be called by the strategist.
	 * @param _rewards The address to use for pulling rewards.
	 */
	function setRewards(address _rewards) external onlyStrategist {
		require(_rewards != address(0));
		vault.approve(rewards, 0);
		rewards = _rewards;
		vault.approve(rewards, uint256(-1));
		emit UpdatedRewards(_rewards);
	}

	/**
	 * @notice
	 *  Used to change `minReportDelay`. `minReportDelay` is the minimum number
	 *  of blocks that should pass for `harvest()` to be called.
	 *
	 *  For external keepers (such as the Keep3r network), this is the minimum
	 *  time between jobs to wait. (see `harvestTrigger()`
	 *  for more details.)
	 *
	 *  This may only be called by governance or the strategist.
	 * @param _delay The minimum number of seconds to wait between harvests.
	 */
	function setMinReportDelay(uint256 _delay) external onlyAuthorized {
		minReportDelay = _delay;
		emit UpdatedMinReportDelay(_delay);
	}

	/**
	 * @notice
	 *  Used to change `maxReportDelay`. `maxReportDelay` is the maximum number
	 *  of blocks that should pass for `harvest()` to be called.
	 *
	 *  For external keepers (such as the Keep3r network), this is the maximum
	 *  time between jobs to wait. (see `harvestTrigger()`
	 *  for more details.)
	 *
	 *  This may only be called by governance or the strategist.
	 * @param _delay The maximum number of seconds to wait between harvests.
	 */
	function setMaxReportDelay(uint256 _delay) external onlyAuthorized {
		maxReportDelay = _delay;
		emit UpdatedMaxReportDelay(_delay);
	}

	/**
	 * @notice
	 *  Used to change `profitFactor`. `profitFactor` is used to determine
	 *  if it's worthwhile to harvest, given gas costs. (See `harvestTrigger()`
	 *  for more details.)
	 *
	 *  This may only be called by governance or the strategist.
	 * @param _profitFactor A ratio to multiply anticipated
	 * `harvest()` gas cost against.
	 */
	function setProfitFactor(uint256 _profitFactor) external onlyAuthorized {
		profitFactor = _profitFactor;
		emit UpdatedProfitFactor(_profitFactor);
	}

	/**
	 * @notice
	 *  Sets how far the Strategy can go into loss without a harvest and report
	 *  being required.
	 *
	 *  By default this is 0, meaning any losses would cause a harvest which
	 *  will subsequently report the loss to the Vault for tracking. (See
	 *  `harvestTrigger()` for more details.)
	 *
	 *  This may only be called by governance or the strategist.
	 * @param _debtThreshold How big of a loss this Strategy may carry without
	 * being required to report to the Vault.
	 */
	function setDebtThreshold(uint256 _debtThreshold) external onlyAuthorized {
		debtThreshold = _debtThreshold;
		emit UpdatedDebtThreshold(_debtThreshold);
	}

	/**
	 * @notice
	 *  Used to change `metadataURI`. `metadataURI` is used to store the URI
	 * of the file describing the strategy.
	 *
	 *  This may only be called by governance or the strategist.
	 * @param _metadataURI The URI that describe the strategy.
	 */
	function setMetadataURI(string calldata _metadataURI) external onlyAuthorized {
		metadataURI = _metadataURI;
		emit UpdatedMetadataURI(_metadataURI);
	}

	/**
	 * Resolve governance address from Vault contract, used to make assertions
	 * on protected functions in the Strategy.
	 */
	function governance() internal view returns (address) {
		return vault.governance();
	}

	/**
	 * @notice
	 *  Provide an accurate conversion from `_amtInWei` (denominated in wei)
	 *  to `want` (using the native decimal characteristics of `want`).
	 * @dev
	 *  Care must be taken when working with decimals to assure that the conversion
	 *  is compatible. As an example:
	 *
	 *      given 1e17 wei (0.1 ETH) as input, and want is USDC (6 decimals),
	 *      with USDC/ETH = 1800, this should give back 1800000000 (180 USDC)
	 *
	 * @param _amtInWei The amount (in wei/1e-18 ETH) to convert to `want`
	 * @return The amount in `want` of `_amtInEth` converted to `want`
	 **/
	function ethToWant(uint256 _amtInWei) public view virtual returns (uint256);

	/**
	 * @notice
	 *  Provide an accurate estimate for the total amount of assets
	 *  (principle + return) that this Strategy is currently managing,
	 *  denominated in terms of `want` tokens.
	 *
	 *  This total should be "realizable" e.g. the total value that could
	 *  *actually* be obtained from this Strategy if it were to divest its
	 *  entire position based on current on-chain conditions.
	 * @dev
	 *  Care must be taken in using this function, since it relies on external
	 *  systems, which could be manipulated by the attacker to give an inflated
	 *  (or reduced) value produced by this function, based on current on-chain
	 *  conditions (e.g. this function is possible to influence through
	 *  flashloan attacks, oracle manipulations, or other DeFi attack
	 *  mechanisms).
	 *
	 *  It is up to governance to use this function to correctly order this
	 *  Strategy relative to its peers in the withdrawal queue to minimize
	 *  losses for the Vault based on sudden withdrawals. This value should be
	 *  higher than the total debt of the Strategy and higher than its expected
	 *  value to be "safe".
	 * @return The estimated total assets in this Strategy.
	 */
	function estimatedTotalAssets() public view virtual returns (uint256);

	/*
	 * @notice
	 *  Provide an indication of whether this strategy is currently "active"
	 *  in that it is managing an active position, or will manage a position in
	 *  the future. This should correlate to `harvest()` activity, so that Harvest
	 *  events can be tracked externally by indexing agents.
	 * @return True if the strategy is actively managing a position.
	 */
	function isActive() public view returns (bool) {
		return vault.strategies(address(this)).debtRatio > 0 || estimatedTotalAssets() > 0;
	}

	/**
	 * Perform any Strategy unwinding or other calls necessary to capture the
	 * "free return" this Strategy has generated since the last time its core
	 * position(s) were adjusted. Examples include unwrapping extra rewards.
	 * This call is only used during "normal operation" of a Strategy, and
	 * should be optimized to minimize losses as much as possible.
	 *
	 * This method returns any realized profits and/or realized losses
	 * incurred, and should return the total amounts of profits/losses/debt
	 * payments (in `want` tokens) for the Vault's accounting (e.g.
	 * `want.balanceOf(this) >= _debtPayment + _profit`).
	 *
	 * `_debtOutstanding` will be 0 if the Strategy is not past the configured
	 * debt limit, otherwise its value will be how far past the debt limit
	 * the Strategy is. The Strategy's debt limit is configured in the Vault.
	 *
	 * NOTE: `_debtPayment` should be less than or equal to `_debtOutstanding`.
	 *       It is okay for it to be less than `_debtOutstanding`, as that
	 *       should only used as a guide for how much is left to pay back.
	 *       Payments should be made to minimize loss from slippage, debt,
	 *       withdrawal fees, etc.
	 *
	 * See `vault.debtOutstanding()`.
	 */
	function prepareReturn(uint256 _debtOutstanding)
		internal
		virtual
		returns (
			uint256 _profit,
			uint256 _loss,
			uint256 _debtPayment
		);

	/**
	 * Perform any adjustments to the core position(s) of this Strategy given
	 * what change the Vault made in the "investable capital" available to the
	 * Strategy. Note that all "free capital" in the Strategy after the report
	 * was made is available for reinvestment. Also note that this number
	 * could be 0, and you should handle that scenario accordingly.
	 *
	 * See comments regarding `_debtOutstanding` on `prepareReturn()`.
	 */
	function adjustPosition(uint256 _debtOutstanding) internal virtual;

	/**
	 * Liquidate up to `_amountNeeded` of `want` of this strategy's positions,
	 * irregardless of slippage. Any excess will be re-invested with `adjustPosition()`.
	 * This function should return the amount of `want` tokens made available by the
	 * liquidation. If there is a difference between them, `_loss` indicates whether the
	 * difference is due to a realized loss, or if there is some other situation at play
	 * (e.g. locked funds) where the amount made available is less than what is needed.
	 *
	 * NOTE: The invariant `_liquidatedAmount + _loss <= _amountNeeded` should always be maintained
	 */
	function liquidatePosition(uint256 _amountNeeded)
		internal
		virtual
		returns (uint256 _liquidatedAmount, uint256 _loss);

	/**
	 * Liquidate everything and returns the amount that got freed.
	 * This function is used during emergency exit instead of `prepareReturn()` to
	 * liquidate all of the Strategy's positions back to the Vault.
	 */

	function liquidateAllPositions() internal virtual returns (uint256 _amountFreed);

	/**
	 * @notice
	 *  Provide a signal to the keeper that `tend()` should be called. The
	 *  keeper will provide the estimated gas cost that they would pay to call
	 *  `tend()`, and this function should use that estimate to make a
	 *  determination if calling it is "worth it" for the keeper. This is not
	 *  the only consideration into issuing this trigger, for example if the
	 *  position would be negatively affected if `tend()` is not called
	 *  shortly, then this can return `true` even if the keeper might be
	 *  "at a loss" (keepers are always reimbursed by Yearn).
	 * @dev
	 *  `callCostInWei` must be priced in terms of `wei` (1e-18 ETH).
	 *
	 *  This call and `harvestTrigger()` should never return `true` at the same
	 *  time.
	 * @param callCostInWei The keeper's estimated gas cost to call `tend()` (in wei).
	 * @return `true` if `tend()` should be called, `false` otherwise.
	 */
	function tendTrigger(uint256 callCostInWei) public view virtual returns (bool) {
		// We usually don't need tend, but if there are positions that need
		// active maintenance, overriding this function is how you would
		// signal for that.
		// If your implementation uses the cost of the call in want, you can
		// use uint256 callCost = ethToWant(callCostInWei);

		return false;
	}

	/**
	 * @notice
	 *  Adjust the Strategy's position. The purpose of tending isn't to
	 *  realize gains, but to maximize yield by reinvesting any returns.
	 *
	 *  See comments on `adjustPosition()`.
	 *
	 *  This may only be called by governance, the strategist, or the keeper.
	 */
	function tend() external onlyKeepers {
		// Don't take profits with this call, but adjust for better gains
		adjustPosition(vault.debtOutstanding());
	}

	/**
	 * @notice
	 *  Provide a signal to the keeper that `harvest()` should be called. The
	 *  keeper will provide the estimated gas cost that they would pay to call
	 *  `harvest()`, and this function should use that estimate to make a
	 *  determination if calling it is "worth it" for the keeper. This is not
	 *  the only consideration into issuing this trigger, for example if the
	 *  position would be negatively affected if `harvest()` is not called
	 *  shortly, then this can return `true` even if the keeper might be "at a
	 *  loss" (keepers are always reimbursed by Yearn).
	 * @dev
	 *  `callCostInWei` must be priced in terms of `wei` (1e-18 ETH).
	 *
	 *  This call and `tendTrigger` should never return `true` at the
	 *  same time.
	 *
	 *  See `min/maxReportDelay`, `profitFactor`, `debtThreshold` to adjust the
	 *  strategist-controlled parameters that will influence whether this call
	 *  returns `true` or not. These parameters will be used in conjunction
	 *  with the parameters reported to the Vault (see `params`) to determine
	 *  if calling `harvest()` is merited.
	 *
	 *  It is expected that an external system will check `harvestTrigger()`.
	 *  This could be a script run off a desktop or cloud bot (e.g.
	 *  https://github.com/iearn-finance/yearn-vaults/blob/main/scripts/keep.py),
	 *  or via an integration with the Keep3r network (e.g.
	 *  https://github.com/Macarse/GenericKeep3rV2/blob/master/contracts/keep3r/GenericKeep3rV2.sol).
	 * @param callCostInWei The keeper's estimated gas cost to call `harvest()` (in wei).
	 * @return `true` if `harvest()` should be called, `false` otherwise.
	 */
	function harvestTrigger(uint256 callCostInWei) public view virtual returns (bool) {
		uint256 callCost = ethToWant(callCostInWei);
		StrategyParams memory params = vault.strategies(address(this));

		// Should not trigger if Strategy is not activated
		if (params.activation == 0) return false;

		// Should not trigger if we haven't waited long enough since previous harvest
		if (block.timestamp.sub(params.lastReport) < minReportDelay) return false;

		// Should trigger if hasn't been called in a while
		if (block.timestamp.sub(params.lastReport) >= maxReportDelay) return true;

		// If some amount is owed, pay it back
		// NOTE: Since debt is based on deposits, it makes sense to guard against large
		//       changes to the value from triggering a harvest directly through user
		//       behavior. This should ensure reasonable resistance to manipulation
		//       from user-initiated withdrawals as the outstanding debt fluctuates.
		uint256 outstanding = vault.debtOutstanding();
		if (outstanding > debtThreshold) return true;

		// Check for profits and losses
		uint256 total = estimatedTotalAssets();
		// Trigger if we have a loss to report
		if (total.add(debtThreshold) < params.totalDebt) return true;

		uint256 profit = 0;
		if (total > params.totalDebt) profit = total.sub(params.totalDebt); // We've earned a profit!

		// Otherwise, only trigger if it "makes sense" economically (gas cost
		// is <N% of value moved)
		uint256 credit = vault.creditAvailable();
		return (profitFactor.mul(callCost) < credit.add(profit));
	}

	/**
	 * @notice
	 *  Harvests the Strategy, recognizing any profits or losses and adjusting
	 *  the Strategy's position.
	 *
	 *  In the rare case the Strategy is in emergency shutdown, this will exit
	 *  the Strategy's position.
	 *
	 *  This may only be called by governance, the strategist, or the keeper.
	 * @dev
	 *  When `harvest()` is called, the Strategy reports to the Vault (via
	 *  `vault.report()`), so in some cases `harvest()` must be called in order
	 *  to take in profits, to borrow newly available funds from the Vault, or
	 *  otherwise adjust its position. In other cases `harvest()` must be
	 *  called to report to the Vault on the Strategy's position, especially if
	 *  any losses have occurred.
	 */
	function harvest() external onlyKeepers {
		uint256 profit = 0;
		uint256 loss = 0;
		uint256 debtOutstanding = vault.debtOutstanding();
		uint256 debtPayment = 0;
		if (emergencyExit) {
			// Free up as much capital as possible
			uint256 amountFreed = liquidateAllPositions();
			if (amountFreed < debtOutstanding) {
				loss = debtOutstanding.sub(amountFreed);
			} else if (amountFreed > debtOutstanding) {
				profit = amountFreed.sub(debtOutstanding);
			}
			debtPayment = debtOutstanding.sub(loss);
		} else {
			// Free up returns for Vault to pull
			(profit, loss, debtPayment) = prepareReturn(debtOutstanding);
		}

		// Allow Vault to take up to the "harvested" balance of this contract,
		// which is the amount it has earned since the last time it reported to
		// the Vault.
		uint256 totalDebt = vault.strategies(address(this)).totalDebt;
		debtOutstanding = vault.report(profit, loss, debtPayment);

		// Check if free returns are left, and re-invest them
		adjustPosition(debtOutstanding);

		// call healthCheck contract
		if (doHealthCheck && healthCheck != address(0)) {
			require(
				HealthCheck(healthCheck).check(profit, loss, debtPayment, debtOutstanding, totalDebt),
				"!healthcheck"
			);
		} else {
			doHealthCheck = true;
		}

		emit Harvested(profit, loss, debtPayment, debtOutstanding);
	}

	/**
	 * @notice
	 *  Withdraws `_amountNeeded` to `vault`.
	 *
	 *  This may only be called by the Vault.
	 * @param _amountNeeded How much `want` to withdraw.
	 * @return _loss Any realized losses
	 */
	function withdraw(uint256 _amountNeeded) external returns (uint256 _loss) {
		require(msg.sender == address(vault), "!vault");
		// Liquidate as much as possible to `want`, up to `_amountNeeded`
		uint256 amountFreed;
		(amountFreed, _loss) = liquidatePosition(_amountNeeded);
		// Send it directly back (NOTE: Using `msg.sender` saves some gas here)
		want.safeTransfer(msg.sender, amountFreed);
		// NOTE: Reinvest anything leftover on next `tend`/`harvest`
	}

	/**
	 * Do anything necessary to prepare this Strategy for migration, such as
	 * transferring any reserve or LP tokens, CDPs, or other tokens or stores of
	 * value.
	 */
	function prepareMigration(address _newStrategy) internal virtual;

	/**
	 * @notice
	 *  Transfers all `want` from this Strategy to `_newStrategy`.
	 *
	 *  This may only be called by the Vault.
	 * @dev
	 * The new Strategy's Vault must be the same as this Strategy's Vault.
	 *  The migration process should be carefully performed to make sure all
	 * the assets are migrated to the new address, which should have never
	 * interacted with the vault before.
	 * @param _newStrategy The Strategy to migrate to.
	 */
	function migrate(address _newStrategy) external {
		require(msg.sender == address(vault));
		require(BaseStrategy(_newStrategy).vault() == vault);
		prepareMigration(_newStrategy);
		want.safeTransfer(_newStrategy, want.balanceOf(address(this)));
	}

	/**
	 * @notice
	 *  Activates emergency exit. Once activated, the Strategy will exit its
	 *  position upon the next harvest, depositing all funds into the Vault as
	 *  quickly as is reasonable given on-chain conditions.
	 *
	 *  This may only be called by governance or the strategist.
	 * @dev
	 *  See `vault.setEmergencyShutdown()` and `harvest()` for further details.
	 */
	function setEmergencyExit() external onlyEmergencyAuthorized {
		emergencyExit = true;
		vault.revokeStrategy();

		emit EmergencyExitEnabled();
	}

	/**
	 * Override this to add all tokens/tokenized positions this contract
	 * manages on a *persistent* basis (e.g. not just for swapping back to
	 * want ephemerally).
	 *
	 * NOTE: Do *not* include `want`, already included in `sweep` below.
	 *
	 * Example:
	 * ```
	 *    function protectedTokens() internal override view returns (address[] memory) {
	 *      address[] memory protected = new address[](3);
	 *      protected[0] = tokenA;
	 *      protected[1] = tokenB;
	 *      protected[2] = tokenC;
	 *      return protected;
	 *    }
	 * ```
	 */
	function protectedTokens() internal view virtual returns (address[] memory);

	/**
	 * @notice
	 *  Removes tokens from this Strategy that are not the type of tokens
	 *  managed by this Strategy. This may be used in case of accidentally
	 *  sending the wrong kind of token to this Strategy.
	 *
	 *  Tokens will be sent to `governance()`.
	 *
	 *  This will fail if an attempt is made to sweep `want`, or any tokens
	 *  that are protected by this Strategy.
	 *
	 *  This may only be called by governance.
	 * @dev
	 *  Implement `protectedTokens()` to specify any additional tokens that
	 *  should be protected from sweeping in addition to `want`.
	 * @param _token The token to transfer out of this vault.
	 */
	function sweep(address _token) external onlyGovernance {
		require(_token != address(want), "!want");
		require(_token != address(vault), "!shares");

		address[] memory _protectedTokens = protectedTokens();
		for (uint256 i; i < _protectedTokens.length; i++)
			require(_token != _protectedTokens[i], "!protected");

		IERC20(_token).safeTransfer(governance(), IERC20(_token).balanceOf(address(this)));
	}
}

abstract contract BaseStrategyInitializable is BaseStrategy {
	bool public isOriginal = true;
	event Cloned(address indexed clone);

	constructor(address _vault) public BaseStrategy(_vault) {}

	function initialize(
		address _vault,
		address _strategist,
		address _rewards,
		address _keeper
	) external virtual {
		_initialize(_vault, _strategist, _rewards, _keeper);
	}

	function clone(address _vault) external returns (address) {
		require(isOriginal, "!clone");
		return this.clone(_vault, msg.sender, msg.sender, msg.sender);
	}

	function clone(
		address _vault,
		address _strategist,
		address _rewards,
		address _keeper
	) external returns (address newStrategy) {
		// Copied from https://github.com/optionality/clone-factory/blob/master/contracts/CloneFactory.sol
		bytes20 addressBytes = bytes20(address(this));

		assembly {
			// EIP-1167 bytecode
			let clone_code := mload(0x40)
			mstore(clone_code, 0x3d602d80600a3d3981f3363d3d373d3d3d363d73000000000000000000000000)
			mstore(add(clone_code, 0x14), addressBytes)
			mstore(
				add(clone_code, 0x28),
				0x5af43d82803e903d91602b57fd5bf30000000000000000000000000000000000
			)
			newStrategy := create(0, clone_code, 0x37)
		}

		BaseStrategyInitializable(newStrategy).initialize(_vault, _strategist, _rewards, _keeper);

		emit Cloned(newStrategy);
	}
}

/**
 * @dev Interface of the ERC20 standard as defined in the EIP.
 */
interface IERC20 {
    /**
     * @dev Returns the amount of tokens in existence.
     */
    function totalSupply() external view returns (uint256);

    /**
     * @dev Returns the amount of tokens owned by `account`.
     */
    function balanceOf(address account) external view returns (uint256);

    /**
     * @dev Moves `amount` tokens from the caller's account to `recipient`.
     *
     * Returns a boolean value indicating whether the operation succeeded.
     *
     * Emits a {Transfer} event.
     */
    function transfer(address recipient, uint256 amount)
        external
        returns (bool);

    /**
     * @dev Returns the remaining number of tokens that `spender` will be
     * allowed to spend on behalf of `owner` through {transferFrom}. This is
     * zero by default.
     *
     * This value changes when {approve} or {transferFrom} are called.
     */
    function allowance(address owner, address spender)
        external
        view
        returns (uint256);

    /**
     * @dev Sets `amount` as the allowance of `spender` over the caller's tokens.
     *
     * Returns a boolean value indicating whether the operation succeeded.
     *
     * IMPORTANT: Beware that changing an allowance with this method brings the risk
     * that someone may use both the old and the new allowance by unfortunate
     * transaction ordering. One possible solution to mitigate this race
     * condition is to first reduce the spender's allowance to 0 and set the
     * desired value afterwards:
     * https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
     *
     * Emits an {Approval} event.
     */
    function approve(address spender, uint256 amount) external returns (bool);

    /**
     * @dev Moves `amount` tokens from `sender` to `recipient` using the
     * allowance mechanism. `amount` is then deducted from the caller's
     * allowance.
     *
     * Returns a boolean value indicating whether the operation succeeded.
     *
     * Emits a {Transfer} event.
     */
    function transferFrom(
        address sender,
        address recipient,
        uint256 amount
    ) external returns (bool);

    /**
     * @dev Emitted when `value` tokens are moved from one account (`from`) to
     * another (`to`).
     *
     * Note that `value` may be zero.
     */
    event Transfer(address indexed from, address indexed to, uint256 value);

    /**
     * @dev Emitted when the allowance of a `spender` for an `owner` is set by
     * a call to {approve}. `value` is the new allowance.
     */
    event Approval(
        address indexed owner,
        address indexed spender,
        uint256 value
    );
}

/**
 * @dev Wrappers over Solidity's arithmetic operations with added overflow
 * checks.
 *
 * Arithmetic operations in Solidity wrap on overflow. This can easily result
 * in bugs, because programmers usually assume that an overflow raises an
 * error, which is the standard behavior in high level programming languages.
 * `SafeMath` restores this intuition by reverting the transaction when an
 * operation overflows.
 *
 * Using this library instead of the unchecked operations eliminates an entire
 * class of bugs, so it's recommended to use it always.
 */
library SafeMath {
    /**
     * @dev Returns the addition of two unsigned integers, reverting on
     * overflow.
     *
     * Counterpart to Solidity's `+` operator.
     *
     * Requirements:
     *
     * - Addition cannot overflow.
     */
    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a + b;
        require(c >= a, "SafeMath: addition overflow");

        return c;
    }

    /**
     * @dev Returns the subtraction of two unsigned integers, reverting on
     * overflow (when the result is negative).
     *
     * Counterpart to Solidity's `-` operator.
     *
     * Requirements:
     *
     * - Subtraction cannot overflow.
     */
    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        return sub(a, b, "SafeMath: subtraction overflow");
    }

    /**
     * @dev Returns the subtraction of two unsigned integers, reverting with custom message on
     * overflow (when the result is negative).
     *
     * Counterpart to Solidity's `-` operator.
     *
     * Requirements:
     *
     * - Subtraction cannot overflow.
     */
    function sub(
        uint256 a,
        uint256 b,
        string memory errorMessage
    ) internal pure returns (uint256) {
        require(b <= a, errorMessage);
        uint256 c = a - b;

        return c;
    }

    /**
     * @dev Returns the multiplication of two unsigned integers, reverting on
     * overflow.
     *
     * Counterpart to Solidity's `*` operator.
     *
     * Requirements:
     *
     * - Multiplication cannot overflow.
     */
    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
        // benefit is lost if 'b' is also tested.
        // See: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/522
        if (a == 0) {
            return 0;
        }

        uint256 c = a * b;
        require(c / a == b, "SafeMath: multiplication overflow");

        return c;
    }

    /**
     * @dev Returns the integer division of two unsigned integers. Reverts on
     * division by zero. The result is rounded towards zero.
     *
     * Counterpart to Solidity's `/` operator. Note: this function uses a
     * `revert` opcode (which leaves remaining gas untouched) while Solidity
     * uses an invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function div(uint256 a, uint256 b) internal pure returns (uint256) {
        return div(a, b, "SafeMath: division by zero");
    }

    /**
     * @dev Returns the integer division of two unsigned integers. Reverts with custom message on
     * division by zero. The result is rounded towards zero.
     *
     * Counterpart to Solidity's `/` operator. Note: this function uses a
     * `revert` opcode (which leaves remaining gas untouched) while Solidity
     * uses an invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function div(
        uint256 a,
        uint256 b,
        string memory errorMessage
    ) internal pure returns (uint256) {
        require(b > 0, errorMessage);
        uint256 c = a / b;
        // assert(a == b * c + a % b); // There is no case in which this doesn't hold

        return c;
    }

    /**
     * @dev Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
     * Reverts when dividing by zero.
     *
     * Counterpart to Solidity's `%` operator. This function uses a `revert`
     * opcode (which leaves remaining gas untouched) while Solidity uses an
     * invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function mod(uint256 a, uint256 b) internal pure returns (uint256) {
        return mod(a, b, "SafeMath: modulo by zero");
    }

    /**
     * @dev Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
     * Reverts with custom message when dividing by zero.
     *
     * Counterpart to Solidity's `%` operator. This function uses a `revert`
     * opcode (which leaves remaining gas untouched) while Solidity uses an
     * invalid opcode to revert (consuming all remaining gas).
     *
     * Requirements:
     *
     * - The divisor cannot be zero.
     */
    function mod(
        uint256 a,
        uint256 b,
        string memory errorMessage
    ) internal pure returns (uint256) {
        require(b != 0, errorMessage);
        return a % b;
    }
}

import {SafeMath} from "SafeMath.sol";
import {Address} from "Address.sol";
import {IERC20} from "IERC20.sol";

/**
 * @title SafeERC20
 * @dev Wrappers around ERC20 operations that throw on failure (when the token
 * contract returns false). Tokens that return no value (and instead revert or
 * throw on failure) are also supported, non-reverting calls are assumed to be
 * successful.
 * To use this library you can add a `using SafeERC20 for IERC20;` statement to your contract,
 * which allows you to call the safe operations as `token.safeTransfer(...)`, etc.
 */
library SafeERC20 {
    using SafeMath for uint256;
    using Address for address;

    function safeTransfer(
        IERC20 token,
        address to,
        uint256 value
    ) internal {
        _callOptionalReturn(
            token,
            abi.encodeWithSelector(token.transfer.selector, to, value)
        );
    }

    function safeTransferFrom(
        IERC20 token,
        address from,
        address to,
        uint256 value
    ) internal {
        _callOptionalReturn(
            token,
            abi.encodeWithSelector(token.transferFrom.selector, from, to, value)
        );
    }

    /**
     * @dev Deprecated. This function has issues similar to the ones found in
     * {IERC20-approve}, and its usage is discouraged.
     *
     * Whenever possible, use {safeIncreaseAllowance} and
     * {safeDecreaseAllowance} instead.
     */
    function safeApprove(
        IERC20 token,
        address spender,
        uint256 value
    ) internal {
        // safeApprove should only be called when setting an initial allowance,
        // or when resetting it to zero. To increase and decrease it, use
        // 'safeIncreaseAllowance' and 'safeDecreaseAllowance'
        // solhint-disable-next-line max-line-length
        require(
            (value == 0) || (token.allowance(address(this), spender) == 0),
            "SafeERC20: approve from non-zero to non-zero allowance"
        );
        _callOptionalReturn(
            token,
            abi.encodeWithSelector(token.approve.selector, spender, value)
        );
    }

    function safeIncreaseAllowance(
        IERC20 token,
        address spender,
        uint256 value
    ) internal {
        uint256 newAllowance =
            token.allowance(address(this), spender).add(value);
        _callOptionalReturn(
            token,
            abi.encodeWithSelector(
                token.approve.selector,
                spender,
                newAllowance
            )
        );
    }

    function safeDecreaseAllowance(
        IERC20 token,
        address spender,
        uint256 value
    ) internal {
        uint256 newAllowance =
            token.allowance(address(this), spender).sub(
                value,
                "SafeERC20: decreased allowance below zero"
            );
        _callOptionalReturn(
            token,
            abi.encodeWithSelector(
                token.approve.selector,
                spender,
                newAllowance
            )
        );
    }

    /**
     * @dev Imitates a Solidity high-level call (i.e. a regular function call to a contract), relaxing the requirement
     * on the return value: the return value is optional (but if data is returned, it must not be false).
     * @param token The token targeted by the call.
     * @param data The call data (encoded using abi.encode or one of its variants).
     */
    function _callOptionalReturn(IERC20 token, bytes memory data) private {
        // We need to perform a low level call here, to bypass Solidity's return data size checking mechanism, since
        // we're implementing it ourselves. We use {Address.functionCall} to perform this call, which verifies that
        // the target address contains contract code and also asserts for success in the low-level call.

        bytes memory returndata =
            address(token).functionCall(
                data,
                "SafeERC20: low-level call failed"
            );
        if (returndata.length > 0) {
            // Return data is optional
            // solhint-disable-next-line max-line-length
            require(
                abi.decode(returndata, (bool)),
                "SafeERC20: ERC20 operation did not succeed"
            );
        }
    }
}

/**
 * @dev Collection of functions related to the address type
 */
library Address {
    /**
     * @dev Returns true if `account` is a contract.
     *
     * [IMPORTANT]
     * ====
     * It is unsafe to assume that an address for which this function returns
     * false is an externally-owned account (EOA) and not a contract.
     *
     * Among others, `isContract` will return false for the following
     * types of addresses:
     *
     *  - an externally-owned account
     *  - a contract in construction
     *  - an address where a contract will be created
     *  - an address where a contract lived, but was destroyed
     * ====
     */
    function isContract(address account) internal view returns (bool) {
        // According to EIP-1052, 0x0 is the value returned for not-yet created accounts
        // and 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 is returned
        // for accounts without code, i.e. `keccak256('')`
        bytes32 codehash;
        bytes32 accountHash =
            0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            codehash := extcodehash(account)
        }
        return (codehash != accountHash && codehash != 0x0);
    }

    /**
     * @dev Replacement for Solidity's `transfer`: sends `amount` wei to
     * `recipient`, forwarding all available gas and reverting on errors.
     *
     * https://eips.ethereum.org/EIPS/eip-1884[EIP1884] increases the gas cost
     * of certain opcodes, possibly making contracts go over the 2300 gas limit
     * imposed by `transfer`, making them unable to receive funds via
     * `transfer`. {sendValue} removes this limitation.
     *
     * https://diligence.consensys.net/posts/2019/09/stop-using-soliditys-transfer-now/[Learn more].
     *
     * IMPORTANT: because control is transferred to `recipient`, care must be
     * taken to not create reentrancy vulnerabilities. Consider using
     * {ReentrancyGuard} or the
     * https://solidity.readthedocs.io/en/v0.5.11/security-considerations.html#use-the-checks-effects-interactions-pattern[checks-effects-interactions pattern].
     */
    function sendValue(address payable recipient, uint256 amount) internal {
        require(
            address(this).balance >= amount,
            "Address: insufficient balance"
        );

        // solhint-disable-next-line avoid-low-level-calls, avoid-call-value
        (bool success, ) = recipient.call{value: amount}("");
        require(
            success,
            "Address: unable to send value, recipient may have reverted"
        );
    }

    /**
     * @dev Performs a Solidity function call using a low level `call`. A
     * plain`call` is an unsafe replacement for a function call: use this
     * function instead.
     *
     * If `target` reverts with a revert reason, it is bubbled up by this
     * function (like regular Solidity function calls).
     *
     * Returns the raw returned data. To convert to the expected return value,
     * use https://solidity.readthedocs.io/en/latest/units-and-global-variables.html?highlight=abi.decode#abi-encoding-and-decoding-functions[`abi.decode`].
     *
     * Requirements:
     *
     * - `target` must be a contract.
     * - calling `target` with `data` must not revert.
     *
     * _Available since v3.1._
     */
    function functionCall(address target, bytes memory data)
        internal
        returns (bytes memory)
    {
        return functionCall(target, data, "Address: low-level call failed");
    }

    /**
     * @dev Same as {xref-Address-functionCall-address-bytes-}[`functionCall`], but with
     * `errorMessage` as a fallback revert reason when `target` reverts.
     *
     * _Available since v3.1._
     */
    function functionCall(
        address target,
        bytes memory data,
        string memory errorMessage
    ) internal returns (bytes memory) {
        return _functionCallWithValue(target, data, 0, errorMessage);
    }

    /**
     * @dev Same as {xref-Address-functionCall-address-bytes-}[`functionCall`],
     * but also transferring `value` wei to `target`.
     *
     * Requirements:
     *
     * - the calling contract must have an ETH balance of at least `value`.
     * - the called Solidity function must be `payable`.
     *
     * _Available since v3.1._
     */
    function functionCallWithValue(
        address target,
        bytes memory data,
        uint256 value
    ) internal returns (bytes memory) {
        return
            functionCallWithValue(
                target,
                data,
                value,
                "Address: low-level call with value failed"
            );
    }

    /**
     * @dev Same as {xref-Address-functionCallWithValue-address-bytes-uint256-}[`functionCallWithValue`], but
     * with `errorMessage` as a fallback revert reason when `target` reverts.
     *
     * _Available since v3.1._
     */
    function functionCallWithValue(
        address target,
        bytes memory data,
        uint256 value,
        string memory errorMessage
    ) internal returns (bytes memory) {
        require(
            address(this).balance >= value,
            "Address: insufficient balance for call"
        );
        return _functionCallWithValue(target, data, value, errorMessage);
    }

    function _functionCallWithValue(
        address target,
        bytes memory data,
        uint256 weiValue,
        string memory errorMessage
    ) private returns (bytes memory) {
        require(isContract(target), "Address: call to non-contract");

        // solhint-disable-next-line avoid-low-level-calls
        (bool success, bytes memory returndata) =
            target.call{value: weiValue}(data);
        if (success) {
            return returndata;
        } else {
            // Look for revert reason and bubble it up if present
            if (returndata.length > 0) {
                // The easiest way to bubble the revert reason is using memory via assembly

                // solhint-disable-next-line no-inline-assembly
                assembly {
                    let returndata_size := mload(returndata)
                    revert(add(32, returndata), returndata_size)
                }
            } else {
                revert(errorMessage);
            }
        }
    }
}

import {Context} from "Context.sol";
import {SafeMath} from "SafeMath.sol";
import {Address} from "Address.sol";
import {IERC20} from "IERC20.sol";

/**
 * @dev Implementation of the {IERC20} interface.
 *
 * This implementation is agnostic to the way tokens are created. This means
 * that a supply mechanism has to be added in a derived contract using {_mint}.
 * For a generic mechanism see {ERC20PresetMinterPauser}.
 *
 * TIP: For a detailed writeup see our guide
 * https://forum.zeppelin.solutions/t/how-to-implement-erc20-supply-mechanisms/226[How
 * to implement supply mechanisms].
 *
 * We have followed general OpenZeppelin guidelines: functions revert instead
 * of returning `false` on failure. This behavior is nonetheless conventional
 * and does not conflict with the expectations of ERC20 applications.
 *
 * Additionally, an {Approval} event is emitted on calls to {transferFrom}.
 * This allows applications to reconstruct the allowance for all accounts just
 * by listening to said events. Other implementations of the EIP may not emit
 * these events, as it isn't required by the specification.
 *
 * Finally, the non-standard {decreaseAllowance} and {increaseAllowance}
 * functions have been added to mitigate the well-known issues around setting
 * allowances. See {IERC20-approve}.
 */

contract ERC20 is Context, IERC20 {
    using SafeMath for uint256;
    using Address for address;

    mapping(address => uint256) private _balances;

    mapping(address => mapping(address => uint256)) private _allowances;

    uint256 private _totalSupply;

    string private _name;
    string private _symbol;
    uint8 private _decimals;

    /**
     * @dev Sets the values for {name} and {symbol}, initializes {decimals} with
     * a default value of 18.
     *
     * To select a different value for {decimals}, use {_setupDecimals}.
     *
     * All three of these values are immutable: they can only be set once during
     * construction.
     */
    constructor(string memory name, string memory symbol) public {
        _name = name;
        _symbol = symbol;
        _decimals = 18;
    }

    /**
     * @dev Returns the name of the token.
     */
    function name() public view returns (string memory) {
        return _name;
    }

    /**
     * @dev Returns the symbol of the token, usually a shorter version of the
     * name.
     */
    function symbol() public view returns (string memory) {
        return _symbol;
    }

    /**
     * @dev Returns the number of decimals used to get its user representation.
     * For example, if `decimals` equals `2`, a balance of `505` tokens should
     * be displayed to a user as `5,05` (`505 / 10 ** 2`).
     *
     * Tokens usually opt for a value of 18, imitating the relationship between
     * Ether and Wei. This is the value {ERC20} uses, unless {_setupDecimals} is
     * called.
     *
     * NOTE: This information is only used for _display_ purposes: it in
     * no way affects any of the arithmetic of the contract, including
     * {IERC20-balanceOf} and {IERC20-transfer}.
     */
    function decimals() public view returns (uint8) {
        return _decimals;
    }

    /**
     * @dev See {IERC20-totalSupply}.
     */
    function totalSupply() public view override returns (uint256) {
        return _totalSupply;
    }

    /**
     * @dev See {IERC20-balanceOf}.
     */
    function balanceOf(address account) public view override returns (uint256) {
        return _balances[account];
    }

    /**
     * @dev See {IERC20-transfer}.
     *
     * Requirements:
     *
     * - `recipient` cannot be the zero address.
     * - the caller must have a balance of at least `amount`.
     */
    function transfer(address recipient, uint256 amount)
        public
        virtual
        override
        returns (bool)
    {
        _transfer(_msgSender(), recipient, amount);
        return true;
    }

    /**
     * @dev See {IERC20-allowance}.
     */
    function allowance(address owner, address spender)
        public
        view
        virtual
        override
        returns (uint256)
    {
        return _allowances[owner][spender];
    }

    /**
     * @dev See {IERC20-approve}.
     *
     * Requirements:
     *
     * - `spender` cannot be the zero address.
     */
    function approve(address spender, uint256 amount)
        public
        virtual
        override
        returns (bool)
    {
        _approve(_msgSender(), spender, amount);
        return true;
    }

    /**
     * @dev See {IERC20-transferFrom}.
     *
     * Emits an {Approval} event indicating the updated allowance. This is not
     * required by the EIP. See the note at the beginning of {ERC20};
     *
     * Requirements:
     * - `sender` and `recipient` cannot be the zero address.
     * - `sender` must have a balance of at least `amount`.
     * - the caller must have allowance for ``sender``'s tokens of at least
     * `amount`.
     */
    function transferFrom(
        address sender,
        address recipient,
        uint256 amount
    ) public virtual override returns (bool) {
        _transfer(sender, recipient, amount);
        _approve(
            sender,
            _msgSender(),
            _allowances[sender][_msgSender()].sub(
                amount,
                "ERC20: transfer amount exceeds allowance"
            )
        );
        return true;
    }

    /**
     * @dev Atomically increases the allowance granted to `spender` by the caller.
     *
     * This is an alternative to {approve} that can be used as a mitigation for
     * problems described in {IERC20-approve}.
     *
     * Emits an {Approval} event indicating the updated allowance.
     *
     * Requirements:
     *
     * - `spender` cannot be the zero address.
     */
    function increaseAllowance(address spender, uint256 addedValue)
        public
        virtual
        returns (bool)
    {
        _approve(
            _msgSender(),
            spender,
            _allowances[_msgSender()][spender].add(addedValue)
        );
        return true;
    }

    /**
     * @dev Atomically decreases the allowance granted to `spender` by the caller.
     *
     * This is an alternative to {approve} that can be used as a mitigation for
     * problems described in {IERC20-approve}.
     *
     * Emits an {Approval} event indicating the updated allowance.
     *
     * Requirements:
     *
     * - `spender` cannot be the zero address.
     * - `spender` must have allowance for the caller of at least
     * `subtractedValue`.
     */
    function decreaseAllowance(address spender, uint256 subtractedValue)
        public
        virtual
        returns (bool)
    {
        _approve(
            _msgSender(),
            spender,
            _allowances[_msgSender()][spender].sub(
                subtractedValue,
                "ERC20: decreased allowance below zero"
            )
        );
        return true;
    }

    /**
     * @dev Moves tokens `amount` from `sender` to `recipient`.
     *
     * This is internal function is equivalent to {transfer}, and can be used to
     * e.g. implement automatic token fees, slashing mechanisms, etc.
     *
     * Emits a {Transfer} event.
     *
     * Requirements:
     *
     * - `sender` cannot be the zero address.
     * - `recipient` cannot be the zero address.
     * - `sender` must have a balance of at least `amount`.
     */
    function _transfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal virtual {
        require(sender != address(0), "ERC20: transfer from the zero address");
        require(recipient != address(0), "ERC20: transfer to the zero address");

        _beforeTokenTransfer(sender, recipient, amount);

        _balances[sender] = _balances[sender].sub(
            amount,
            "ERC20: transfer amount exceeds balance"
        );
        _balances[recipient] = _balances[recipient].add(amount);
        emit Transfer(sender, recipient, amount);
    }

    /** @dev Creates `amount` tokens and assigns them to `account`, increasing
     * the total supply.
     *
     * Emits a {Transfer} event with `from` set to the zero address.
     *
     * Requirements
     *
     * - `to` cannot be the zero address.
     */
    function _mint(address account, uint256 amount) internal virtual {
        require(account != address(0), "ERC20: mint to the zero address");

        _beforeTokenTransfer(address(0), account, amount);

        _totalSupply = _totalSupply.add(amount);
        _balances[account] = _balances[account].add(amount);
        emit Transfer(address(0), account, amount);
    }

    /**
     * @dev Destroys `amount` tokens from `account`, reducing the
     * total supply.
     *
     * Emits a {Transfer} event with `to` set to the zero address.
     *
     * Requirements
     *
     * - `account` cannot be the zero address.
     * - `account` must have at least `amount` tokens.
     */
    function _burn(address account, uint256 amount) internal virtual {
        require(account != address(0), "ERC20: burn from the zero address");

        _beforeTokenTransfer(account, address(0), amount);

        _balances[account] = _balances[account].sub(
            amount,
            "ERC20: burn amount exceeds balance"
        );
        _totalSupply = _totalSupply.sub(amount);
        emit Transfer(account, address(0), amount);
    }

    /**
     * @dev Sets `amount` as the allowance of `spender` over the `owner`s tokens.
     *
     * This is internal function is equivalent to `approve`, and can be used to
     * e.g. set automatic allowances for certain subsystems, etc.
     *
     * Emits an {Approval} event.
     *
     * Requirements:
     *
     * - `owner` cannot be the zero address.
     * - `spender` cannot be the zero address.
     */
    function _approve(
        address owner,
        address spender,
        uint256 amount
    ) internal virtual {
        require(owner != address(0), "ERC20: approve from the zero address");
        require(spender != address(0), "ERC20: approve to the zero address");

        _allowances[owner][spender] = amount;
        emit Approval(owner, spender, amount);
    }

    /**
     * @dev Sets {decimals} to a value other than the default one of 18.
     *
     * WARNING: This function should only be called from the constructor. Most
     * applications that interact with token contracts will not expect
     * {decimals} to ever change, and may work incorrectly if it does.
     */
    function _setupDecimals(uint8 decimals_) internal {
        _decimals = decimals_;
    }

    /**
     * @dev Hook that is called before any transfer of tokens. This includes
     * minting and burning.
     *
     * Calling conditions:
     *
     * - when `from` and `to` are both non-zero, `amount` of ``from``'s tokens
     * will be to transferred to `to`.
     * - when `from` is zero, `amount` tokens will be minted for `to`.
     * - when `to` is zero, `amount` of ``from``'s tokens will be burned.
     * - `from` and `to` are never both zero.
     *
     * To learn more about hooks, head to xref:ROOT:extending-contracts.adoc#using-hooks[Using Hooks].
     */
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    ) internal virtual {}
}

/*
 * @dev Provides information about the current execution context, including the
 * sender of the transaction and its data. While these are generally available
 * via msg.sender and msg.data, they should not be accessed in such a direct
 * manner, since when dealing with GSN meta-transactions the account sending and
 * paying for execution may not be the actual sender (as far as an application
 * is concerned).
 *
 * This contract is only required for intermediate, library-like contracts.
 */
abstract contract Context {
    function _msgSender() internal view virtual returns (address payable) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes memory) {
        this; // silence state mutability warning without generating bytecode - see https://github.com/ethereum/solidity/issues/2691
        return msg.data;
    }
}

/**
 * @dev Standard math utilities missing in the Solidity language.
 */
library Math {
    /**
     * @dev Returns the largest of two numbers.
     */
    function max(uint256 a, uint256 b) internal pure returns (uint256) {
        return a >= b ? a : b;
    }

    /**
     * @dev Returns the smallest of two numbers.
     */
    function min(uint256 a, uint256 b) internal pure returns (uint256) {
        return a < b ? a : b;
    }

    /**
     * @dev Returns the average of two numbers. The result is rounded towards
     * zero.
     */
    function average(uint256 a, uint256 b) internal pure returns (uint256) {
        // (a + b) / 2 can overflow, so we distribute
        return (a / 2) + (b / 2) + (((a % 2) + (b % 2)) / 2);
    }
}

// SPDX-License-Identifier: AGPL-3.0

pragma solidity 0.6.12;

interface ILpDepositor {
	function balanceOf(address account) external view returns (uint256);

	function earned(address account) external view returns (uint256);

	function deposit(uint256 amount) external;

	function withdrawAll() external;

	function withdraw(uint256 amount) external;

	function getReward() external;

	function TOKEN() external view returns (address);

	function rewardToken() external view returns (address);
}

pragma solidity >=0.6.2;
pragma experimental ABIEncoderV2;

struct route {
	address from;
	address to;
	bool stable;
}

interface IThenaRouter {
	function getAmountOut(
		uint256 amountIn,
		address tokenIn,
		address tokenOut
	) external view returns (uint256 amount, bool stable);

	function quoteAddLiquidity(
		address tokenA,
		address tokenB,
		bool stable,
		uint256 amountADesired,
		uint256 amountBDesired
	)
		external
		view
		returns (
			uint256 amountA,
			uint256 amountB,
			uint256 liquidity
		);

	function quoteRemoveLiquidity(
		address tokenA,
		address tokenB,
		bool stable,
		uint256 liquidity
	) external view returns (uint256 amountA, uint256 amountB);

	function swapExactTokensForTokens(
		uint256 amountIn,
		uint256 amountOutMin,
		route[] calldata routes,
		address to,
		uint256 deadline
	) external returns (uint256[] memory amounts);

	function addLiquidity(
		address tokenA,
		address tokenB,
		bool stable,
		uint256 amountADesired,
		uint256 amountBDesired,
		uint256 amountAMin,
		uint256 amountBMin,
		address to,
		uint256 deadline
	)
		external
		returns (
			uint256 amountA,
			uint256 amountB,
			uint256 liquidity
		);

	function removeLiquidity(
		address tokenA,
		address tokenB,
		bool stable,
		uint256 liquidity,
		uint256 amountAMin,
		uint256 amountBMin,
		address to,
		uint256 deadline
	) external returns (uint256 amountA, uint256 amountB);
}

pragma solidity >=0.6.2;

interface IUniswapV2Router01 {
    function factory() external pure returns (address);

    function WETH() external pure returns (address);

    function addLiquidity(
        address tokenA,
        address tokenB,
        uint256 amountADesired,
        uint256 amountBDesired,
        uint256 amountAMin,
        uint256 amountBMin,
        address to,
        uint256 deadline
    )
        external
        returns (
            uint256 amountA,
            uint256 amountB,
            uint256 liquidity
        );

    function addLiquidityETH(
        address token,
        uint256 amountTokenDesired,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline
    )
        external
        payable
        returns (
            uint256 amountToken,
            uint256 amountETH,
            uint256 liquidity
        );

    function removeLiquidity(
        address tokenA,
        address tokenB,
        uint256 liquidity,
        uint256 amountAMin,
        uint256 amountBMin,
        address to,
        uint256 deadline
    ) external returns (uint256 amountA, uint256 amountB);

    function removeLiquidityETH(
        address token,
        uint256 liquidity,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline
    ) external returns (uint256 amountToken, uint256 amountETH);

    function removeLiquidityWithPermit(
        address tokenA,
        address tokenB,
        uint256 liquidity,
        uint256 amountAMin,
        uint256 amountBMin,
        address to,
        uint256 deadline,
        bool approveMax,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external returns (uint256 amountA, uint256 amountB);

    function removeLiquidityETHWithPermit(
        address token,
        uint256 liquidity,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline,
        bool approveMax,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external returns (uint256 amountToken, uint256 amountETH);

    function swapExactTokensForTokens(
        uint256 amountIn,
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external returns (uint256[] memory amounts);

    function swapTokensForExactTokens(
        uint256 amountOut,
        uint256 amountInMax,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external returns (uint256[] memory amounts);

    function swapExactETHForTokens(
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external payable returns (uint256[] memory amounts);

    function swapTokensForExactETH(
        uint256 amountOut,
        uint256 amountInMax,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external returns (uint256[] memory amounts);

    function swapExactTokensForETH(
        uint256 amountIn,
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external returns (uint256[] memory amounts);

    function swapETHForExactTokens(
        uint256 amountOut,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external payable returns (uint256[] memory amounts);

    function quote(
        uint256 amountA,
        uint256 reserveA,
        uint256 reserveB
    ) external pure returns (uint256 amountB);

    function getAmountOut(
        uint256 amountIn,
        uint256 reserveIn,
        uint256 reserveOut
    ) external pure returns (uint256 amountOut);

    function getAmountIn(
        uint256 amountOut,
        uint256 reserveIn,
        uint256 reserveOut
    ) external pure returns (uint256 amountIn);

    function getAmountsOut(uint256 amountIn, address[] calldata path)
        external
        view
        returns (uint256[] memory amounts);

    function getAmountsIn(uint256 amountOut, address[] calldata path)
        external
        view
        returns (uint256[] memory amounts);
}

interface IUniRouter is IUniswapV2Router01 {
    function removeLiquidityETHSupportingFeeOnTransferTokens(
        address token,
        uint256 liquidity,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline
    ) external returns (uint256 amountETH);

    function removeLiquidityETHWithPermitSupportingFeeOnTransferTokens(
        address token,
        uint256 liquidity,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline,
        bool approveMax,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external returns (uint256 amountETH);

    function swapExactTokensForTokensSupportingFeeOnTransferTokens(
        uint256 amountIn,
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external;

    function swapExactETHForTokensSupportingFeeOnTransferTokens(
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external payable;

    function swapExactTokensForETHSupportingFeeOnTransferTokens(
        uint256 amountIn,
        uint256 amountOutMin,
        address[] calldata path,
        address to,
        uint256 deadline
    ) external;
}

// SPDX-License-Identifier: MIT

pragma solidity >=0.5.0;

interface IV1Pair {
	function totalSupply() external view returns (uint256);

	function transfer(address recipient, uint256 amount) external returns (bool);

	function decimals() external view returns (uint8);

	function symbol() external view returns (string memory);

	function balanceOf(address) external view returns (uint256);

	function approve(address spender, uint256 value) external returns (bool);

	function token0() external view returns (address);

	function token1() external view returns (address);

	function isStable() external view returns (bool);

	function transferFrom(
		address src,
		address dst,
		uint256 amount
	) external returns (bool);

	function permit(
		address owner,
		address spender,
		uint256 value,
		uint256 deadline,
		uint8 v,
		bytes32 r,
		bytes32 s
	) external;

	function swap(
		uint256 amount0Out,
		uint256 amount1Out,
		address to,
		bytes calldata data
	) external;

	function burn(address to) external returns (uint256 amount0, uint256 amount1);

	function mint(address to) external returns (uint256 liquidity);

	function getReserves()
		external
		view
		returns (
			uint112 _reserve0,
			uint112 _reserve1,
			uint32 _blockTimestampLast
		);

	function getAmountOut(uint256, address) external view returns (uint256);

	function current(address tokenIn, uint256 amountIn)
		external
		view
		returns (uint256 amountOut);

	function quote(
		address tokenIn,
		uint256 amountIn,
		uint256 granularity
	) external view returns (uint256 amountOut);
}