pragma solidity ^0.8.16;

import "./ClassicToken.sol";

/**
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
    CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! CUMMIES!!! 
 */
 // SPDX-License-Identifier: MIT
contract Cummies is ClassicToken {

    string private name_ = "CUMMIES!!!";
    string private symbol_ = "CUMMIES!!!";
    uint8 private decimals_ = 9;
    uint256 private supply_ = 10**12 * 10**decimals_;

    constructor() ClassicToken(name_, symbol_, decimals_, supply_) {}

}